title: ""
email: luke@lukeoliff.com
description: >-
  A list of useful RESTful APIs for use in application development.

  All contributions welcome!
baseurl: ""
url: ""
twitter_username: mroliff
github_username:  lukeoliff

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

gems:
  - jekyll-readme-index

readme_index:
  enabled: true
  remove_originals: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"